spring:
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8085

kafka:
  topics:
    order-events: order-events

promotions:
  schedule:
    cron: ${PROMOTIONS_CRON:0 0 10 * * MON} # Every Monday at 10:00 AM

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
