spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dev-aurora-pg.internal.vpc:5432/auth_user_db}
    username: ${SPRING_DATASOURCE_USERNAME:dev_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration-ms: 1800000     # 30 mins in dev
  refresh-token-expiration-ms: 604800000  # 7 days

logging:
  level:
    com.ecommerce: DEBUG
